FROM openjdk:8-jdk-alpine

LABEL Wenjiahu <848063664@qq.com>

WORKDIR /home

COPY target/demo-0.0.1.jar /home/demo-0.0.1.jar

ENTRYPOINT ["java","-jar","-Dspring.profiles.active=prod","/home/demo-0.0.1.jar"]

