kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-log-pvc
  namespace: test
  labels:
    app: demo-log-pvc
  annotations:
    kubesphere.io/alias-name: demo-log
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-server-provisioner
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: 
