kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-log-pvc
  namespace: test
  annotations:
    kubesphere.io/creator: admin
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local
  volumeMode: Filesystem
