apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  namespace: test
  labels:
    app: demo
    app.kubernetes.io/name: licos-industry-app
    app.kubernetes.io/version: v1
spec:
  ports:
    - name: tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: demo
  type: ClusterIP
